聊天室功能說明 - Feat/chat room/issue/5
astrocamp/15th-SyncSquad pull request #12
Opened 2023-12-19 03:42 UTC by TimChaoTW

- 新增聊天室
- 聊天室可以留言，且顯示留言者email。
- 使用廣播聊天室會在不同帳號或瀏覽器同步。

TurboDeviseController參考文章：
https://betterprogramming.pub/devise-auth-setup-in-rails-7-44240aaed4be

https://github.com/astrocamp/15th-SyncSquad/assets/132726143/7709973e-af45-49a9-9c82-88c59b98ab80

2023-12-19 06:49 UTC, ryoma510260 approved these changes

2023-12-19 06:54 UTC, kaochenlong commented on Gemfile
> +gem 'hotwire-rails', '~> 0.1.3'
這什麼東西？

![image](https://github.com/astrocamp/15th-SyncSquad/assets/33090/4c4275d4-728a-40ad-95a8-bbffe8615dad)

2023-12-19 06:56 UTC, TimChaoTW commented on app/controllers/messages_controller.rb
> +    @message = current_user.messages.create(body: msg_params[:body], room_id: params[:room_id])
body 在資料表中表示留言本體，型態是string

2023-12-19 06:57 UTC, TimChaoTW commented on Gemfile
> +gem 'hotwire-rails', '~> 0.1.3'
廣播要用到的套件

2023-12-19 06:58 UTC, kaochenlong commented on Gemfile
> +gem 'hotwire-rails', '~> 0.1.3'
確定嗎？這東西最後更新日期是 2021 年的事了

2023-12-19 07:20 UTC, TimChaoTW commented on Gemfile
> +gem 'hotwire-rails', '~> 0.1.3'
我錯了，根據原作者github：
https://github.com/hotwired/hotwire-rails
這個 gem 原本是聚合 Turbo 和 Stimulus 的依賴關係，但除此之外沒有提供其他功能。
僅僅聚合依賴關係並不足以提供足夠的價值，因此這個 gem 現在已經被棄用了。
實際刪除gem 裡面的的這行，重新bundle後確認不會有影響。
因此這個部分會再重新修正！

2023-12-20 03:58 UTC, Kkrystalll commented on app/models/user.rb
> +  validates_uniqueness_of :name
![image](https://github.com/astrocamp/15th-SyncSquad/assets/100756945/40af9c17-6fce-4b21-ab25-05833c4aa185)
這句會讓註冊無法成功，看是要修改註冊欄位還是這邊要調整～

2023-12-20 04:16 UTC, TimChaoTW commented on Gemfile
> +gem 'hotwire-rails', '~> 0.1.3'
最新進度已修正

2023-12-20 04:23 UTC, Kkrystalll commented on app/controllers/rooms_controller.rb
> +    render 'index'
show 頁面為何會需要 index 的東西？

2023-12-20 04:23 UTC, Kkrystalll commented on app/views/messages/_message.html.erb
> +      <h6 class="name"><%= message.user.email %></h6>
這邊我覺得顯示使用者名稱會比較簡短，但這樣 user name 就會需要必填
不然還有個方法就是擷取 email @ 前
例如：
`krystal@gmail.com`就擷取 email @ 前的 `krystal`

2023-12-20 04:23 UTC, Kkrystalll commented on app/views/messages/_new_message_form.html.erb
> +      <%= f.text_field :body, id: 'chat-text', class: 'block w-full p-4 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 sm:text-md focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-70
![截圖 2023-12-20 下午12 21 54](https://github.com/astrocamp/15th-SyncSquad/assets/100756945/683d7818-c3c0-42bc-8bad-9ceb0207b2fd)
這邊應該要資料送出時，將輸入框內的文字清除

2023-12-20 04:23 UTC, Kkrystalll commented on app/views/rooms/_new_room_form.html.erb
> +  <%= f.text_field :name, class: 'block w-full p-4 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 sm:text-md focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-60
同上，送出文字要清除

2023-12-20 04:23 UTC, Kkrystalll commented on test/fixtures/messages.yml
> +  body: MyText
不需要的檔案可移除

2023-12-20 04:27 UTC, TimChaoTW commented on README.md
> +- run brew service
我的redis和pg 是使用brew install 安裝的
所以brew services可以把redis 和pg開啟

2023-12-20 04:29 UTC, TimChaoTW commented on app/controllers/rooms_controller.rb
> +    render 'index'
我想讓頁面停留在index頁面

2023-12-20 04:29 UTC, TimChaoTW commented on app/models/user.rb
> +  validates_uniqueness_of :name
已修正user.rb

2023-12-20 04:37 UTC, TimChaoTW commented on app/controllers/rooms_controller.rb
> +    render 'index'
我的聊天室頁面都顯示在index上，而show頁面上有很多房間和訊息。
這樣做在index 視圖可能同時處理顯示單個房間的詳細信息和顯示所有房間列表的功能。

2023-12-20 04:38 UTC, TimChaoTW commented on app/views/messages/_message.html.erb
> +      <h6 class="name"><%= message.user.email %></h6>
ok等等來修

2023-12-20 04:38 UTC, TimChaoTW commented on app/views/messages/_new_message_form.html.erb
> +      <%= f.text_field :body, id: 'chat-text', class: 'block w-full p-4 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 sm:text-md focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-70
對這個部分還沒有寫，我想等下一個pr再來修

2023-12-20 04:38 UTC, TimChaoTW commented on test/fixtures/messages.yml
> +  body: MyText
ok

2023-12-20 04:53 UTC, TimChaoTW commented on app/views/messages/_message.html.erb
> +      <h6 class="name"><%= message.user.email %></h6>
![image](https://github.com/astrocamp/15th-SyncSquad/assets/132726143/c8d742f2-832a-421c-a899-cb5ff9d47aab)

2023-12-20 04:59 UTC, TimChaoTW commented on app/controllers/messages_controller.rb
> +    # 紀錄訊息本體與創建訊息的房間
已刪除

2023-12-20 05:00 UTC, TimChaoTW commented on app/views/messages/_message.html.erb
> +      <h6 class="name"><%= message.user.email %></h6>
已上傳修正檔案

2023-12-20 05:02 UTC, TimChaoTW commented on test/fixtures/messages.yml
> +  body: MyText
上傳移除完成

2023-12-21 02:52 UTC, AranceLiu commented on README.md
> +- run brew service
https://redis.io/docs/install/install-redis/install-redis-on-mac-os/

2023-12-21 02:52 UTC, AranceLiu commented on app/views/users/_user.html.erb
這邊 如果我去點人 會壞掉
https://github.com/astrocamp/15th-SyncSquad/assets/145585863/7f59684e-a336-4270-befc-81b06b25ac8c

2023-12-21 02:52 UTC, AranceLiu commented on db/schema.rb
room的名字，要非空？
這樣我建沒有名字聊天室，可以建成，但不能點進去

<img width="1016" alt="Screenshot 0005-12-21 at 10 27 59 AM" src="https://github.com/astrocamp/15th-SyncSquad/assets/145585863/9a7fbe16-3902-40c0-b1d4-946e3b444064">

2023-12-21 02:55 UTC, Kkrystalll commented on README.md
> +- run brew service
我的理解是應該使用專案的人需要先裝好 pg 跟 redis 並將其啟動
但並不是 `run brew service`
@kaochenlong 想問問老師～

2023-12-21 02:56 UTC, AranceLiu commented on README.md
> +- run brew service
我剛剛試下 redis-server
然後 再開專案 才啟動

2023-12-21 02:59 UTC, kaochenlong commented on README.md
> +- run brew service
對使用 Mac 的同學來說，如果 pg 跟 redis 都是靠 homebrew 安裝的話，的確是可以靠 brew 指令來啟動
但對非 Mac 的同學來說就不是了。

README 應該寫的比較泛用一些，例如自行安裝 pg & redis 後，執行 `rails server` 或 `bin/dev` 啟動服務

2023-12-21 03:00 UTC, TimChaoTW commented on db/schema.rb
ok我再來增加驗證，應該要規定非空

2023-12-21 03:32 UTC, TimChaoTW commented on app/views/users/_user.html.erb
對，這個部分是單人聊天。
本來要在這個Pr裡面寫，後來發現Pr太大包所以想放到下一個Pr。
我到時候先註解掉，等下個Pr完成在讓他出來！

2023-12-21 03:42 UTC, TimChaoTW commented on db/schema.rb
我更新了我更新了，謝謝你這個地方我沒注意到
https://github.com/astrocamp/15th-SyncSquad/assets/132726143/4ead2965-4da2-4525-9aca-f75e08c02a70

2023-12-21 04:34 UTC, Kkrystalll commented on app/controllers/rooms_controller.rb
> +    render 'index'
我自己試這句，註解起來跟執行是一樣效果，想問他真的有作用嗎？

2023-12-21 04:41 UTC, Kkrystalll commented on app/controllers/rooms_controller.rb
> +    render 'index'
我理解是 index 頁就是房間列表，可以顯示所有房間； show 頁就是可以顯示這房間裡的對話（可能側邊欄可以看到房間們），所以我覺得他們應該是分開的頁面，不然感覺就做在一頁 show. index 二選一就可以了
@kaochenlong 想求救老師，不使用 show.html.erb ，而是在這邊 `render 'index'` 這樣做法是可以的嗎？

2023-12-21 04:43 UTC, kaochenlong commented on app/controllers/rooms_controller.rb
> +    render 'index'
在 `def index` 方法裡，最後預設的行為就是 render 同名的 view，也就是 `render 'index``，所以除非是要顯示別的頁面，不然可以不用特別寫

2023-12-21 04:50 UTC, kaochenlong commented on app/controllers/rooms_controller.rb
> +    render 'index'
然後，如果在 show 頁面需要資料的話，比較常見的做法是 render 一包 JSON 回去，再由前端自己想辦法處理

2023-12-21 05:30 UTC, TimChaoTW commented on app/controllers/rooms_controller.rb
> +    render 'index'
那我new action 的```render 'index'```先移除，
show如果需要優化我想等聊天室功能比較完整再來執行。

2023-12-21 23:59 UTC, Liu-Yun-Syuan requested changes

2023-12-22 03:26 UTC, AranceLiu approved these changes

2023-12-22 04:21 UTC, TimChaoTW commented on db/schema.rb
> message 也需要非空喔

ok 新增了
https://github.com/astrocamp/15th-SyncSquad/assets/132726143/4791cf72-484e-410d-a251-a3c58e5ab38f

2023-12-22 04:22 UTC, TimChaoTW commented on app/views/rooms/index.html.erb
> +  <h3 class="text-2xl pt-1 text-cyan-600">歡迎 <%= current_user.email.split("@").first %> ლ(╹◡╹ლ)</h3>
> 這裡直接取得 `current_user.name` 或是 `current_user.nick_name` 就可以了。

已經完成

2023-12-22 08:27 UTC, Liu-Yun-Syuan approved these changes

2023-12-22 08:27 UTC, merged