新增單人聊天室、聊天室css排版、聊天室留言區分自己與別人css
astrocamp/15th-SyncSquad pull request #35
Opened 2023-12-24 17:15 UTC by TimChaoTW

額外建立model Participant 紀錄單人聊天室的關聯
- belongs_to :user
- belongs_to :room

https://github.com/astrocamp/15th-SyncSquad/assets/132726143/24b9e154-f2ad-4ce8-8a49-d82ef86fcb27

新增首頁連結：回到首頁、聊天室

https://github.com/astrocamp/15th-SyncSquad/assets/132726143/5382c9de-65c0-4735-810e-e9dd3665bf18

2023-12-24 17:28 UTC, TimChaoTW commented on app/models/message.rb
> +    return unless room.is_private
如果不是私人聊天室就不進行檢查

2023-12-24 17:30 UTC, TimChaoTW commented on app/models/message.rb
> +    throw :abort unless is_participant
如果發現一個不是聊天室參與者的使用者試圖發送訊息，則拋出一個中止訊息的操作，防止訊息被創建。

2023-12-24 17:33 UTC, TimChaoTW commented on app/models/room.rb
> +  def self.create_private_room(users, room_name)
這個方法是寫給user_controller ->show action用的，
因為只有點了使用者名稱才會創建私人聊天室。

2023-12-24 18:51 UTC, TimChaoTW commented on app/models/room.rb
> +      Participant.create(user_id: user.id, room_id: single_room.id)
每當建立一個單人留言/聊天，就會建立兩個Participant，圖片中有兩個單人聊天室。
分別紀錄兩個 user_id ：@user, current_user
<img width="300" alt="截圖 2023-12-25 02 50 29" src="https://github.com/astrocamp/15th-SyncSquad/assets/132726143/2a56c532-5766-4bf3-87c2-c4406b8a1f74">

2023-12-25 07:33 UTC, Liu-Yun-Syuan requested changes

2023-12-26 02:28 UTC, Kkrystalll commented
![截圖 2023-12-26 上午10 25 53](https://github.com/astrocamp/15th-SyncSquad/assets/100756945/1f5d6592-2a6f-47cd-9539-30690fe55ef2)

想問 create 聊天室之後要怎麼知道這是單人聊天室還是多人聊天室？
我現在用三個帳號登入
1. 我看不知來這是單人還是多人聊天室
2. ui/ux 怪怪的，可以看圖片是兩個不同的人在傳訊息，但是都在右邊

2023-12-26 02:30 UTC, Kkrystalll commented
另外全站的所有版面目前都滿陽春的，如果對於設計沒有想法，建議直接找一個復刻對象，照著他切

2023-12-26 02:42 UTC, TimChaoTW commented
> ![截圖 2023-12-26 上午10 25 53](https://private-user-images.githubusercontent.com/100756945/292792428-1f5d6592-2a6f-47cd-9539-30690fe55ef2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NTg2MjAsIm5iZiI6MTcwMzU1ODMyMCwicGF0aCI6Ii8xMDA3NTY5NDUvMjkyNzkyNDI4LTFmNWQ2NTkyLTJhNmYtNDdjZC05NTM5LTMwNjkwZmU1NWVmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQwMjM4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGYyM2E2MWZkM2M3OWI5ZTRiZDM0NTBjYmE4MzYwZmU4OTE2NDViMDczY2M1YjZiMDg4YTQxYmFkYjFlMzdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KdEiciSujvXWuGlpmlCWne0L-B8fjt9qythRxCIJauE)
> 
> 想問 create 聊天室之後要怎麼知道這是單人聊天室還是多人聊天室？ 我現在用三個帳號登入
> 
> 1. 我看不知來這是單人還是多人聊天室
> 2. ui/ux 怪怪的，可以看圖片是兩個不同的人在傳訊息，但是都在右邊

這邊單人聊天和多人聊天的區別在於，單人聊天就是1 on 1所以點擊左側的user＿name即可建立只有兩人發話的聊天室。
而自己用room_name 創建的聊天室（目前設定為公開聊天室），每一個登入帳號都可以進入

2023-12-26 02:43 UTC, TimChaoTW commented
> 另外全站的所有版面目前都滿陽春的，如果對於設計沒有想法，建議直接找一個復刻對象，照著他切

目前是打算往line的方向前進，我再來找找看有沒有好一點的範例

2023-12-26 02:43 UTC, Kkrystalll commented on app/controllers/users_controller.rb
> +    @rooms = Room.public_rooms
目前看起來所有都是 `public_rooms`
是不是應該考慮怎樣不公開，也可以另外開票

2023-12-26 02:43 UTC, Kkrystalll commented on app/controllers/users_controller.rb
> +  def get_name(user1, user2)
想問這個方法目的是要做什麼？

2023-12-26 02:43 UTC, Kkrystalll commented on app/controllers/users_controller.rb
> +    @single_room = Room.where(name: @room_name).first || Room.create_private_room([@user, current_user], @room_name)
記得你 room 的 name 有做 `uniqueness: true` 
那這邊
```ruby
Room.where(name: @room_name).first
```
就不用用 where 再 first，直接用 find_by 就好了

2023-12-26 02:44 UTC, Kkrystalll commented
> > 另外全站的所有版面目前都滿陽春的，如果對於設計沒有想法，建議直接找一個復刻對象，照著他切
> 
> 目前是打算往line的方向前進，我再來找找看有沒有好一點的範例

往 line 的方向可以，但可能要再切得更像一點，目前還看不太出來是 line

2023-12-26 02:47 UTC, TimChaoTW commented
> 這邊單人聊天和多人聊天的區別在於，單人聊天就是1 on 1所以點擊左側的user＿name即可建立只有兩人發話的聊天室。
BTW 如果有別人有非1對1聊天室的成員試圖發話（可能透過網址或其他方式進入聊天室），他會被message model攔下

2023-12-26 02:49 UTC, TimChaoTW commented on app/controllers/users_controller.rb
> +  def get_name(user1, user2)
當我點擊聊天對象用聊天對象的id和我的id製作一個聊天室名稱，而且利用排序讓互相的聊天室名稱都是一樣的

2023-12-26 03:03 UTC, TimChaoTW commented
我的好像還能區分耶😂
![image](https://github.com/astrocamp/15th-SyncSquad/assets/132726143/46bcb82c-95b9-4cab-94c5-3ca7dfa69860)

2023-12-26 03:04 UTC, TimChaoTW commented on app/controllers/users_controller.rb
> +    @single_room = Room.where(name: @room_name).first || Room.create_private_room([@user, current_user], @room_name)
ok我再來調整

2023-12-26 03:52 UTC, Kkrystalll commented on app/controllers/users_controller.rb
> +    @messages = @single_room.messages.order(created_at: :asc)
也可以寫成
```ruby
@messages = @single_room.messages.order(:created_at)
```

2023-12-26 03:52 UTC, Kkrystalll commented on app/helpers/users_helper.rb
> +end
不用的檔案可以移除

2023-12-26 03:52 UTC, Kkrystalll commented on app/models/message.rb
> +    is_participant = Participant.where(user_id: user.id, room_id: room.id).first
這一樣可以使用 find_by，可以簡化如下

```ruby
is_participant = Participant.find_by(:user, :room)
```

2023-12-26 03:52 UTC, Kkrystalll commented on app/models/message.rb
> +    throw :abort unless is_participant
想問問怎樣的情況可以發上述說的不是聊天室參與者的使用者試圖發送訊息

2023-12-26 03:52 UTC, Kkrystalll commented on app/models/participant.rb
> +class Participant < ApplicationRecord
想問這個 model 主要是做什麼用的？

2023-12-26 03:52 UTC, Kkrystalll commented on app/models/room.rb
> +  # after_create_commit { broadcast_append_to 'rooms' }
註解不要就拿掉

2023-12-26 04:13 UTC, Kkrystalll commented on app/controllers/users_controller.rb
> +  def show
這邊把單人聊天室做在 user 的 show 頁面滿奇怪的
個人想向網址可能是 `/chat/:id` 之類的
這樣會更清楚，可以調整一下路徑

2023-12-26 04:13 UTC, Kkrystalll commented on app/models/user.rb
>    devise :database_authenticatable, :registerable,
上面 4.5 行註解不要就刪掉

2023-12-26 04:13 UTC, Kkrystalll commented on app/views/layouts/_navbar.html.erb
> +                    <a href="http://localhost:5000/main/home" class="block px-3 py-2 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500" aria-current="page
這裡應該寫相對路徑，這樣寫 `http://localhost:5000/main/home` 上正式機會直接錯掉

2023-12-26 04:13 UTC, Kkrystalll commented on app/views/layouts/application.html.erb
> +      background-color: #007bff !important;
這邊有什麼特別原因要寫 style 還要用到 !important ？

2023-12-26 04:13 UTC, Kkrystalll commented on app/views/messages/_message.html.erb
> +<div class="cont-<%=message.user.id%>">
養成好的習慣
```ruby
<%=message.user.id%>
```
空格空好
```ruby
<%= message.user.id %>
```

下面也是

2023-12-26 04:13 UTC, Kkrystalll commented on app/views/rooms/index.html.erb
> +    <% if @single_room.is_private%>
這裡兩層判斷可以整理一下

2023-12-26 04:13 UTC, Kkrystalll commented on test/controllers/users_controller_test.rb
> +end
不用的檔案可以移除

2023-12-26 04:23 UTC, Kkrystalll commented on app/controllers/users_controller.rb
> +    "private_#{user[0].id}_#{user[1].id}"
想問為何要做出 `"private_#{user[0].id}_#{user[1].id}"` 然後寫入 room 的 name?

2023-12-27 07:23 UTC, TimChaoTW commented on app/controllers/users_controller.rb
> +    @rooms = Room.public_rooms
> 目前看起來所有都是 `public_rooms` 是不是應該考慮怎樣不公開，也可以另外開票

這個可以做但有點複雜我可以開個票先

2023-12-27 07:25 UTC, AranceLiu approved these changes

2023-12-27 07:27 UTC, TimChaoTW commented on app/controllers/users_controller.rb
> +    @messages = @single_room.messages.order(created_at: :asc)
因為:asc是預設值吧！ok等等來修

2023-12-27 07:29 UTC, TimChaoTW commented on app/views/layouts/_navbar.html.erb
> +                    <a href="http://localhost:5000/main/home" class="block px-3 py-2 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500" aria-current="page
ok!等等來改

2023-12-27 16:38 UTC, ryoma510260 approved these changes

2023-12-28 06:14 UTC, TimChaoTW commented on app/controllers/users_controller.rb
> +  def show
ok我再來開票

2023-12-28 06:43 UTC, TimChaoTW commented on app/models/message.rb
> +    throw :abort unless is_participant
假設別的登入者透過網址進入？

2023-12-28 06:47 UTC, TimChaoTW commented on app/controllers/users_controller.rb
> +    "private_#{user[0].id}_#{user[1].id}"
目的是讓我密你或你密我都可以指向同一個房間
假設user _id:5的我密user _id:3的你
我麼的聊天是房間名稱就會是private_3_5
你密我也是找這個聊天室讓我們聊天、留言

2023-12-28 14:20 UTC, TimChaoTW commented on app/models/user.rb
> +  has_many :events
完成！

2023-12-28 14:20 UTC, TimChaoTW commented on app/controllers/users_controller.rb
> +    @single_room = Room.where(name: @room_name).first || Room.create_private_room([@user, current_user], @room_name)
完成！

2023-12-28 14:20 UTC, TimChaoTW commented on app/controllers/users_controller.rb
> +    @messages = @single_room.messages.order(created_at: :asc)
完成！

2023-12-28 14:21 UTC, TimChaoTW commented on app/helpers/users_helper.rb
> +end
完成！

2023-12-28 14:21 UTC, TimChaoTW commented on app/models/message.rb
> +    is_participant = Participant.where(user_id: user.id, room_id: room.id).first
完成！

2023-12-28 14:22 UTC, TimChaoTW commented on app/models/room.rb
> +  # after_create_commit { broadcast_append_to 'rooms' }
完成！

2023-12-28 14:22 UTC, TimChaoTW commented on app/models/user.rb
>    devise :database_authenticatable, :registerable,
完成！

2023-12-28 14:22 UTC, TimChaoTW commented on app/views/layouts/_navbar.html.erb
> +                    <a href="http://localhost:5000/main/home" class="block px-3 py-2 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500" aria-current="page
完成！

2023-12-28 14:23 UTC, TimChaoTW commented on app/views/layouts/application.html.erb
> +      background-color: #007bff !important;
當時在試tailwind先放這個，
修改完成！

2023-12-28 14:24 UTC, TimChaoTW commented on app/views/messages/_message.html.erb
> +<div class="cont-<%=message.user.id%>">
完成！

2023-12-28 14:38 UTC, TimChaoTW commented on app/views/rooms/index.html.erb
> +    <% if @single_room.is_private%>
兩層變一層嗎？好像有困難
如果用三元運算子可以簡化這段code但是可讀性會降低

2023-12-29 08:49 UTC, Kkrystalll commented on app/views/rooms/index.html.erb
> +    <% if @single_room.is_private%>
這邊第一個建議是可以使用 partial render ，例如建一個 `_single_room.html.erb` ，這樣這邊就可以改成如下，且將第一個 if 判斷式放進去
```ruby
<%= render partial: 'single_room', locals: { single_room: @single_room, messages: @messages, user: @user } if @single_room %>
```

2023-12-29 08:54 UTC, Kkrystalll commented on app/views/rooms/index.html.erb
> +    <% if @single_room.is_private%>
接著裡面第二個 if 判斷式
```ruby
<% if @single_room.is_private %>
        <h4 class="text-center"> <%= @user&.email.split("@").first%> </h4>
<% else %>
        <h4 class="text-center"> <%= @single_room.name %> </h4>
<% end %>  
```

有兩個建議，第一個就是改三元運算子，因為樣式一樣
```ruby
<h4 class="text-center"><%= @single_room.is_private ? @user&.email.split("@").first : @single_room.name %> </h4>
```
如果擔心可讀性不好，那第二個就是在 helper 寫方法

2023-12-29 11:23 UTC, AranceLiu approved these changes

2023-12-30 00:44 UTC, Liu-Yun-Syuan commented on app/models/message.rb
> +    throw :abort unless is_participant
那是不是要直接跳到類似 404 的空畫面？

2023-12-30 00:51 UTC, Liu-Yun-Syuan approved these changes

2023-12-30 02:15 UTC, ryoma510260 approved these changes

2023-12-30 02:16 UTC, merged