Issue/31 - 為聊天室新增markdown語法支援 與 程式碼highlight 功能
astrocamp/15th-SyncSquad pull request #42
Opened 2023-12-28 04:32 UTC by TimChaoTW

https://github.com/astrocamp/15th-SyncSquad/assets/132726143/cfa8e729-d55f-4414-86eb-6a8a1f5a48dc

2023-12-28 10:10 UTC, AranceLiu submitted a review, later dismissed

2023-12-28 10:10 UTC, AranceLiu commented on app/views/rooms/index.html.erb
不小心加了空白列

2023-12-28 11:03 UTC, Liu-Yun-Syuan requested changes

2023-12-28 14:57 UTC, TimChaoTW commented on test/models/message_test.rb
> +end
完成！

2023-12-28 14:57 UTC, TimChaoTW commented on test/fixtures/messages.yml
> +  body: MyText
完成！

2023-12-28 14:57 UTC, TimChaoTW commented on app/views/rooms/index.html.erb
完成！

2023-12-28 14:59 UTC, AranceLiu approved these changes

2023-12-29 11:21 UTC, Liu-Yun-Syuan approved these changes

2023-12-30 02:32 UTC, ryoma510260 approved these changes

2023-12-30 04:59 UTC, merged