Issue/49 新增員工權限
astrocamp/15th-SyncSquad pull request #83
Opened 2024-01-07 02:37 UTC by ryoma510260

1.[公司登入後可進到三大功能頁](https://youtu.be/bAo6eQXXLNU)
2.[經由網址到新增員工頁面，顯示為權限不足](https://youtu.be/xsN17Wiw7CE)
3.[授權"公司已登入"+"員工角色為HR" 才能新增員工](https://youtu.be/OmieVFuYctE)
4.補以上頁面 I18n

2024-01-08 02:32 UTC, Kkrystalll commented on app/controllers/application_controller.rb
> +    @current_company || Company.find_by(id: session[:__company_ticket__])
想問這個 `@current_company` 是哪來的？

2024-01-08 02:33 UTC, Kkrystalll commented
會比較建議用 [pundit](https://github.com/varvet/pundit) 這種權限管理套件來做網站全站的權限

2024-01-10 02:44 UTC, AranceLiu approved these changes

2024-01-11 18:29 UTC, TimChaoTW requested changes
麻煩修正回authenticate_user!

2024-01-11 18:29 UTC, TimChaoTW commented on app/controllers/events_controller.rb
> +  before_action :authenticate_or_company_signed_in!
authenticate_or_company_signed_in!會報錯
請改回authenticate_user!，因為這邊的公司不是user裡面的資料不符合project 和room controllers的邏輯

https://github.com/astrocamp/15th-SyncSquad/assets/132726143/ee27d24b-c075-4c92-a897-7e138bb6491b

2024-01-11 18:29 UTC, TimChaoTW commented on app/controllers/projects_controller.rb
> +  before_action :authenticate_or_company_signed_in!
同上

2024-01-11 18:29 UTC, TimChaoTW commented on app/controllers/rooms_controller.rb
> +  before_action :authenticate_or_company_signed_in!
同上

2024-01-12 02:56 UTC, closed without merging